import type { Metadata } from "next";
import localFont from "next/font/local";
import { GoogleOAuthProvider } from '@react-oauth/google';
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import ClientProviders from "./components/ClientProviders";

const queryClient = new QueryClient()

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       
         <QueryClientProvider client={queryClient}>
        <GoogleOAuthProvider clientId="1014199154400-aegosauitpcng63h8sn6ekkcepeifjk5.apps.googleusercontent.com">
           {children}
            <Toaster />
            <ReactQueryDevtools />
          </GoogleOAuthProvider>
        </QueryClientProvider>
       
           
      </body>
    </html>
  );
}
